/**
 * Role permissions for the backend
 * Defines which permissions each role has
 */

const { PERMISSIONS } = require('./permissions');

// Map roles to permissions
exports.ROLE_PERMISSIONS = {
  // Admin has ALL permissions - automatically gets every single permission
  admin: Object.values(PERMISSIONS),

  // User (Single Role SaaS) - Same as admin/owner
  user: Object.values(PERMISSIONS),

  // Manager has most permissions except critical system admin functions
  manager: Object.values(PERMISSIONS).filter(
    permission => !permission.startsWith('system:') &&
      !permission.startsWith('backup:') &&
      permission !== PERMISSIONS.USERS_DELETE &&
      permission !== PERMISSIONS.ROLES_DELETE &&
      permission !== PERMISSIONS.SETTINGS_DELETE
  ),

  // Accountant has financial and reporting focus with comprehensive accounting permissions
  accountant: [
    // User viewing
    PERMISSIONS.USERS_VIEW,

    // Inventory viewing
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.CATEGORIES_VIEW,

    // Customer and supplier management
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_CREATE,
    PERMISSIONS.SUPPLIERS_EDIT,

    // Sales management
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_EDIT,
    PERMISSIONS.SALE_ORDER_VIEW,
    PERMISSIONS.SALE_ORDER_CREATE,
    PERMISSIONS.SALE_ORDER_EDIT,
    PERMISSIONS.SALE_INVOICE_VIEW,
    PERMISSIONS.SALE_INVOICE_CREATE,
    PERMISSIONS.SALE_INVOICE_EDIT,
    PERMISSIONS.SALE_INVOICE_APPROVE,
    PERMISSIONS.SALE_PAYMENT_VIEW,
    PERMISSIONS.SALE_PAYMENT_CREATE,
    PERMISSIONS.SALE_PAYMENT_EDIT,
    PERMISSIONS.SALE_RETURN_VIEW,
    PERMISSIONS.SALE_RETURN_CREATE,
    PERMISSIONS.SALE_RETURN_EDIT,
    PERMISSIONS.DELIVERY_VIEW,

    // Purchase management
    PERMISSIONS.PURCHASE_VIEW,
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.PURCHASE_EDIT,
    PERMISSIONS.PURCHASE_APPROVE,
    PERMISSIONS.PURCHASE_ORDER_VIEW,
    PERMISSIONS.PURCHASE_ORDER_CREATE,
    PERMISSIONS.PURCHASE_ORDER_EDIT,
    PERMISSIONS.PURCHASE_ORDER_APPROVE,
    PERMISSIONS.PURCHASE_INVOICE_VIEW,
    PERMISSIONS.PURCHASE_INVOICE_CREATE,
    PERMISSIONS.PURCHASE_INVOICE_EDIT,
    PERMISSIONS.PURCHASE_INVOICE_APPROVE,
    PERMISSIONS.PURCHASE_REQUISITION_VIEW,
    PERMISSIONS.PURCHASE_REQUISITION_CREATE,
    PERMISSIONS.PURCHASE_REQUISITION_EDIT,
    PERMISSIONS.PURCHASE_RECEIPT_VIEW,
    PERMISSIONS.PURCHASE_RECEIPT_CREATE,
    PERMISSIONS.PURCHASE_RECEIPT_EDIT,

    // GRN management
    PERMISSIONS.GRN_VIEW,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.GRN_EDIT,
    PERMISSIONS.GRN_APPROVE,

    // Stock operations
    PERMISSIONS.STOCK_ADJUSTMENT_VIEW,
    PERMISSIONS.STOCK_ADJUSTMENT_CREATE,
    PERMISSIONS.STOCK_ADJUSTMENT_EDIT,
    PERMISSIONS.STOCK_TRANSFER_VIEW,
    PERMISSIONS.STOCK_ALERT_VIEW,

    // Comprehensive accounting permissions
    PERMISSIONS.ACCOUNTING_VIEW,
    PERMISSIONS.ACCOUNTING_CREATE,
    PERMISSIONS.ACCOUNTING_EDIT,
    PERMISSIONS.ACCOUNTS_PAYABLE_VIEW,
    PERMISSIONS.ACCOUNTS_PAYABLE_CREATE,
    PERMISSIONS.ACCOUNTS_PAYABLE_EDIT,
    PERMISSIONS.ACCOUNTS_RECEIVABLE_VIEW,
    PERMISSIONS.ACCOUNTS_RECEIVABLE_CREATE,
    PERMISSIONS.ACCOUNTS_RECEIVABLE_EDIT,
    PERMISSIONS.JOURNAL_ENTRY_VIEW,
    PERMISSIONS.JOURNAL_ENTRY_CREATE,
    PERMISSIONS.JOURNAL_ENTRY_EDIT,
    PERMISSIONS.JOURNAL_ENTRY_APPROVE,

    // All reporting permissions
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_CREATE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.FINANCIAL_REPORTS_VIEW,
    PERMISSIONS.FINANCIAL_REPORTS_CREATE,
    PERMISSIONS.FINANCIAL_REPORTS_EXPORT,
    PERMISSIONS.SALES_REPORTS_VIEW,
    PERMISSIONS.SALES_REPORTS_CREATE,
    PERMISSIONS.SALES_REPORTS_EXPORT,
    PERMISSIONS.PURCHASE_REPORTS_VIEW,
    PERMISSIONS.PURCHASE_REPORTS_CREATE,
    PERMISSIONS.PURCHASE_REPORTS_EXPORT,

    // Settings viewing
    PERMISSIONS.SETTINGS_VIEW,
  ],

  // Salesperson has sales and customer management focus
  salesperson: [
    // Inventory viewing
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.CATEGORIES_VIEW,

    // Customer management
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,

    // Sales management
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_EDIT,
    PERMISSIONS.SALE_ORDER_VIEW,
    PERMISSIONS.SALE_ORDER_CREATE,
    PERMISSIONS.SALE_ORDER_EDIT,
    PERMISSIONS.SALE_INVOICE_VIEW,
    PERMISSIONS.SALE_INVOICE_CREATE,
    PERMISSIONS.SALE_INVOICE_EDIT,
    PERMISSIONS.SALE_PAYMENT_VIEW,
    PERMISSIONS.SALE_PAYMENT_CREATE,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_EDIT,
    PERMISSIONS.DELIVERY_VIEW,
    PERMISSIONS.DELIVERY_CREATE,
    PERMISSIONS.DELIVERY_EDIT,

    // Stock adjustments
    PERMISSIONS.STOCK_ADJUSTMENT_VIEW,
    PERMISSIONS.STOCK_ADJUSTMENT_CREATE,
    PERMISSIONS.STOCK_ALERT_VIEW,
    // Self-service leave
    PERMISSIONS.LEAVE_SELF,

    // Sales reporting
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.SALES_REPORTS_VIEW,
    // Projects basic access for sales where applicable
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.TASKS_VIEW,
    // CRM access for sales
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_EDIT,
    PERMISSIONS.CRM_SEND,
  ],

  // Staff has basic view permissions
  staff: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALE_ORDER_VIEW,
    PERMISSIONS.PURCHASE_VIEW,
    PERMISSIONS.PURCHASE_ORDER_VIEW,
    PERMISSIONS.STOCK_ADJUSTMENT_VIEW,
    PERMISSIONS.STOCK_ALERT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    // Self-service leave
    PERMISSIONS.LEAVE_SELF,
    // Allow viewing projects/tasks
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.TASKS_VIEW,
    // CRM access for sales
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_EDIT,
    PERMISSIONS.CRM_SEND,
  ],

  // Warehouse Manager for inventory and stock operations
  warehouse_manager: [
    // Full inventory management
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_EDIT,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.WAREHOUSE_CREATE,
    PERMISSIONS.WAREHOUSE_EDIT,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.CATEGORIES_CREATE,
    PERMISSIONS.CATEGORIES_EDIT,

    // Stock operations
    PERMISSIONS.STOCK_ADJUSTMENT_VIEW,
    PERMISSIONS.STOCK_ADJUSTMENT_CREATE,
    PERMISSIONS.STOCK_ADJUSTMENT_EDIT,
    PERMISSIONS.STOCK_TRANSFER_VIEW,
    PERMISSIONS.STOCK_TRANSFER_CREATE,
    PERMISSIONS.STOCK_TRANSFER_EDIT,
    PERMISSIONS.STOCK_ALERT_VIEW,
    PERMISSIONS.STOCK_ALERT_CREATE,
    PERMISSIONS.STOCK_ALERT_EDIT,
    PERMISSIONS.STOCK_ALERT_MANAGE,

    // GRN management
    PERMISSIONS.GRN_VIEW,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.GRN_EDIT,
    PERMISSIONS.GRN_APPROVE,

    // Purchase receipt management
    PERMISSIONS.PURCHASE_RECEIPT_VIEW,
    PERMISSIONS.PURCHASE_RECEIPT_CREATE,
    PERMISSIONS.PURCHASE_RECEIPT_EDIT,

    // Supplier viewing
    PERMISSIONS.SUPPLIERS_VIEW,

    // Reporting
    PERMISSIONS.REPORTS_VIEW,
    // Optional: view tasks for cross-team ops
    PERMISSIONS.TASKS_VIEW,
    // CRM access for sales
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_EDIT,
    PERMISSIONS.CRM_SEND,
  ]
};


